npm run e2es login
npm run e2es signup
npm run e2es invalidSingup
npm run e2es checkLeagues
npm run e2es createSeason
npm run e2es createEvent
npm run e2es createTeam
npm run e2es addRound
npm run e2es createDivision
npm run e2es createTourSchema
npm run e2es createTournament
npm run e2es createBrackets
npm run e2es publishTeam
npm run e2es addMembership
npm run e2es addQuestionnaire
